<?php
declare(strict_types=1);

/**
 * /auth.php (site root)
 * Central session + auth helpers for michaelwidener.com.
 *
 * NOTE: This file must NOT echo/print anything.
 * It is included by pages that send HTML and headers.
 */

/* ============================
   1) CONFIGURE YOUR LOGIN HERE
   ============================ */

/**
 * Plaintext username (current/simple mode).
 * - Leave this set if you want the classic "username in auth.php" setup.
 * - If you later fill HC_LOGIN_USERNAME_HASH below, the hash will be used instead (and this becomes a fallback).
 */
define('HC_LOGIN_USERNAME', 'michael'); // case-sensitive

/**
 * Optional: concealed username mode (recommended).
 * Paste a bcrypt hash of your username here (generated by make-user.php).
 * If this is NON-empty, auth will verify the typed username via password_verify()
 * and your plaintext username becomes a fallback.
 */
define('HC_LOGIN_USERNAME_HASH', ''); // e.g. '$2y$12$....' (leave '' to disable)

/**
 * Password hash (required).
 * Paste your bcrypt password hash here (generated by make-user.php or make-password.php).
 */
define('HC_LOGIN_PASSWORD_HASH', ''); // e.g. '$2y$12$....' (required)


define('HC_LOGIN_USERNAME_HASH', ''); // optional: paste bcrypt hash of username here (leave '' to use plaintext HC_LOGIN_USERNAME)


/* ============================
   2) SESSION BOOTSTRAP
   ============================ */

if (session_status() !== PHP_SESSION_ACTIVE) {

    // Ensure session cookie applies to the whole site (NOT /legal only)
    $secure = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off');

    // Use array syntax when available (PHP 7.3+). If host is older, it will ignore and still run.
    if (PHP_VERSION_ID >= 70300) {
        session_set_cookie_params([
            'lifetime' => 0,
            'path'     => '/',
            'secure'   => $secure,
            'httponly' => true,
            'samesite' => 'Lax',
        ]);
    } else {
        // Legacy fallback
        session_set_cookie_params(0, '/; samesite=Lax', '', $secure, true);
    }

    @ini_set('session.use_strict_mode', '1');
    @ini_set('session.use_only_cookies', '1');
    @ini_set('session.cookie_httponly', '1');
    @ini_set('session.cookie_secure', $secure ? '1' : '0');

    session_start();
}

/* ============================
   2B) NAV HISTORY (JS-LESS BACK)
   ============================ */

function nav_track_visit(): void
{
    if (session_status() !== PHP_SESSION_ACTIVE) return;

    $current = $_SERVER['REQUEST_URI'] ?? '/';
    if (!is_string($current) || $current === '') $current = '/';
    if ($current[0] !== '/') $current = '/';

    // First hit
    if (!isset($_SESSION['nav_current'])) {
        $_SESSION['nav_prev'] = null;
        $_SESSION['nav_current'] = $current;
        $_SESSION['nav_next'] = null; // placeholder
        return;
    }

    // Refresh: don't change history
    if ($_SESSION['nav_current'] === $current) {
        return;
    }

    // Move current to prev, set new current
    $_SESSION['nav_prev'] = $_SESSION['nav_current'];
    $_SESSION['nav_current'] = $current;

    // Forward is intentionally conservative unless you later implement it
    $_SESSION['nav_next'] = null;
}

// Track every request that includes auth.php
nav_track_visit();

function nav_back_href(string $fallback = '/'): string
{
    $prev = $_SESSION['nav_prev'] ?? null;
    if (!is_string($prev) || $prev === '') return $fallback;
    if ($prev[0] !== '/') return $fallback;
    return $prev;
}

function nav_forward_href(string $fallback = '/'): string
{
    $next = $_SESSION['nav_next'] ?? null;
    if (!is_string($next) || $next === '') return $fallback;
    if ($next[0] !== '/') return $fallback;
    return $next;
}

/* ============================
   3) CORE HELPERS
   ============================ */

function is_logged_in(): bool
{
    return (!empty($_SESSION['logged_in']) && $_SESSION['logged_in'] === true)
        || (!empty($_SESSION['hc_logged_in']) && $_SESSION['hc_logged_in'] === true);
}

function login_user(): void
{
    // Prevent session fixation
    session_regenerate_id(true);

    // Canonical + legacy compatibility
    $_SESSION['logged_in'] = true;
    $_SESSION['hc_logged_in'] = true;
}

function logout_user(): void
{
    $_SESSION = [];

    if (ini_get('session.use_cookies')) {
        $params = session_get_cookie_params();
        setcookie(
            session_name(),
            '',
            time() - 42000,
            $params['path'] ?? '/',
            $params['domain'] ?? '',
            (bool)($params['secure'] ?? false),
            (bool)($params['httponly'] ?? true)
        );
    }

    session_destroy();
}

function redirect(string $path): void
{
    header('Location: ' . $path);
    exit;
}

/**
 * Allow only local site paths for "next" to prevent open-redirects.
 */
function get_next_path(string $default = '/'): string
{
    $next = '';

    if (isset($_GET['next']) && is_string($_GET['next'])) {
        $next = $_GET['next'];
    } elseif (isset($_POST['next']) && is_string($_POST['next'])) {
        $next = $_POST['next'];
    }

    $next = trim($next);
    if ($next === '') return $default;

    // Must be absolute-path on this site, like "/legal/" (not "http://...")
    if ($next[0] !== '/') return $default;

    // prevent scheme-relative redirects
    if (function_exists('str_starts_with') && str_starts_with($next, '//')) return $default;

    return $next;
}

function redirect_to_login(string $next = '/'): void
{
    redirect('/login/?next=' . rawurlencode($next));
}

function require_login(?string $next_override = null): void
{
    if (is_logged_in()) return;

    $next = $next_override;
    if ($next === null || $next === '') {
        $next = $_SERVER['REQUEST_URI'] ?? '/';
        if (!is_string($next) || $next === '') $next = '/';
    }

    redirect_to_login($next);
}

/**
 * Credential verification used by login pages.
 *
 * Gentle behavior:
 * - Password hash is required.
 * - Username check works in either mode:
 *    (A) plaintext username via HC_LOGIN_USERNAME (default)
 *    (B) concealed username via HC_LOGIN_USERNAME_HASH (if non-empty)
 *      In concealed mode, the plaintext username becomes a fallback.
 */

function auth_check_credentials(string $username, string $password): bool
{
    $username = trim($username);
    $password = (string)$password;

    if (!defined('HC_LOGIN_PASSWORD_HASH')) return false;

    $pass_hash = (string)HC_LOGIN_PASSWORD_HASH;
    if ($pass_hash === '') return false;

    // Password must verify
    if (!password_verify($password, $pass_hash)) {
        return false;
    }

    // Optional concealed username mode
    $user_hash = defined('HC_LOGIN_USERNAME_HASH') ? (string)HC_LOGIN_USERNAME_HASH : '';
    if ($user_hash !== '') {
        if (password_verify($username, $user_hash)) {
            return true;
        }
        // Fall through to plaintext fallback if provided
    }

    // Plaintext username mode (fallback / default)
    if (!defined('HC_LOGIN_USERNAME')) return false;

    $u = (string)HC_LOGIN_USERNAME;
    if ($u === '') return false;

    return hash_equals($u, $username);
}
