$(document).ready(function(){
    $("#anim3-top-image").click(function(){
        $("#anim3 img.top").toggleClass("transparent");
        $("#soundtrack1")[0].pause();
        $("#soundtrack2")[0].pause();
        $("#soundtrack3")[0].play();
        $("#soundtrack4")[0].pause();
        $("#soundtrack5")[0].pause();
        $("#soundtrack6")[0].pause();
        $("#soundtrack7")[0].pause();
        $("#soundtrack8")[0].pause();
        $("#soundtrack9")[0].pause();
        $("#soundtrack10")[0].pause();
        $("#soundtrack11")[0].pause();
    });
$("#anim3-top-image").dblclick(function(){
    $("#soundtrack3")[0].pause();
    });
});